import React from 'react';
import SubNav from '../../Components/SubNav';

const TermsOfService = () => {
  const sections = [
    { id: "acceptance", title: "Acceptance of Terms" },
    { id: "eligibility", title: "Eligibility" },
    { id: "account", title: "Account Registration" },
    { id: "platform", title: "Platform for Transaction" },
    { id: "conduct", title: "Use of the Website" },
    { id: "content", title: "Seller & Proprietary Content" },
    { id: "privacy", title: "Privacy" },
    { id: "liability", title: "Limitation of Liability" },
    { id: "jurisdiction", title: "Law and Jurisdiction" },
  ];

  return (
    <div className="bg-white min-h-screen">
      {/* Banner Header */}
      <div className="bg-[#F2EBE3] pt-32 pb-24 px-6 md:px-12 text-center">
        <h1 className="text-4xl md:text-6xl font-serif text-stone-900 tracking-tight">Terms of Service</h1>
      </div>

      {/* Secondary Navigation */}
      <SubNav active="Terms of Service" />

      <div className="max-w-6xl mx-auto flex flex-col lg:flex-row gap-16 pt-24 pb-20 px-6 md:px-12 lg:px-24">
        
        {/* Table of Contents - Hidden on mobile */}
        <aside className="hidden lg:block w-64 shrink-0 h-fit sticky top-32">
          <h4 className="text-[12px] font-bold uppercase tracking-[0.2em] text-stone-900 mb-6 pb-2 border-b border-stone-100">Sections</h4>
          <nav className="flex flex-col gap-4 text-[13px] text-stone-400">
            {sections.map(sec => (
              <a key={sec.id} href={`#${sec.id}`} className="hover:text-stone-900 transition-colors">{sec.title}</a>
            ))}
          </nav>
        </aside>

        {/* Content Section */}
        <main className="flex-grow max-w-3xl">
          <header className="mb-12">
            <h1 className="text-3xl md:text-5xl font-serif italic text-stone-900 mb-4">Terms of Service</h1>
            <p className="text-stone-400 text-sm italic font-light">Last Updated: April 17, 2026</p>
          </header>

          <div className="prose prose-stone max-w-none text-[15px] leading-relaxed text-stone-600 font-light space-y-10">
            
            <section className="space-y-4">
              <p>
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
              <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Musawwir Art website.
              </p>
            </section>

            <section id="acceptance" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">1. Acceptance of Terms</h2>
              <p>
                The domain name www.musawwir.art (hereinafter referred to as “Website”) is owned by Musawwir Art Private Limited, a company incorporated under the Companies Act, 2013 with its registered office at #198, CMH Road, 2nd Floor, Suite No.783, Indiranagar, Bangalore – 560038, Karnataka, India (hereinafter referred to as “Musawwir Art”).
              </p>
              <p>
                Musawwir Art provides a service for selling original works of art (the “Services”) through the Website. These Terms of Use (the “Terms”) are intended to make you aware of your legal rights and responsibilities with respect to your access to and use of the Website and any related applications.
              </p>
              <p>
                By accessing or using the Website, you are agreeing to these Terms and concluding a legally binding contract with Musawwir Art Private Limited.
              </p>
            </section>

            <section id="eligibility" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">2. Eligibility</h2>
              <p>
                Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” including minors (under 18 years) are not eligible to use the Website. As a minor, if you wish to use or transact on the Website, such use or transaction may be made by your legal guardian or parents.
              </p>
            </section>

            <section id="account" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">3. Account Registration</h2>
              <p>
                In order to make a purchase, you must first create an account (“Account“) by completing our registration process. You agree to provide accurate, current and complete information. Musawwir Art reserves the right to suspend or terminate your Account if any information provided proves to be inaccurate or incomplete. You are responsible for safeguarding your password and for any activities under your Account.
              </p>
            </section>

            <section id="platform" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">4. Platform for Transaction and Communication</h2>
              <p>
                The Website is a platform that Users utilize to meet and interact with one another for their transactions. Musawwir Art is not and cannot be a party to or control in any manner any transaction between the Website’s Users.
              </p>
              <ul className="list-disc pl-5 space-y-3">
                <li>All contractual terms are offered by and agreed to between Buyers and Sellers alone.</li>
                <li>Musawwir Art does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products proposed to be sold.</li>
                <li>Musawwir Art is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers.</li>
                <li>We use commercially reasonable efforts to display the colors of Original Works of Art accurately. However, we are not responsible for the color accuracy on individual computer monitors.</li>
              </ul>
            </section>

            <section id="conduct" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">5. Use of the Website</h2>
              <p>
                You agree that Your use of Website shall be strictly governed by binding principles. You shall not host, display, upload, modify, publish, transmit, update or share any information which:
              </p>
              <ul className="list-disc pl-5 space-y-3">
                <li>Belongs to another person and to which You do not have any right.</li>
                <li>Is grossly harmful, harassing, defamatory, obscene, or otherwise unlawful.</li>
                <li>Is misleading in any way or promotes illegal activities.</li>
                <li>Infringes upon or violates any third party’s rights including intellectual property rights.</li>
                <li>Contains software viruses or any other computer code designed to interrupt the functionality of any computer resource.</li>
              </ul>
            </section>

            <section id="content" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">6. Proprietary Rights</h2>
              <p>
                The Website, Services and Musawwir Art Content are protected by copyright, trademark and other laws of India and foreign countries. Musawwir Art and its licensors exclusively own all right, title and interest in and to the Website and Services.
              </p>
              <p>
                Musawwir Art authorizes you to download, view and print Musawwir Art-owned Content solely for your personal use in visiting the Website. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights except those expressly granted.
              </p>
            </section>

            <section id="privacy" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">7. Privacy</h2>
              <p>
                We view protection of Your privacy as a very important principle. We store and process Your Information in accordance with Information Technology Act 2000 and Rules there under. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.
              </p>
            </section>

            <section id="liability" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">8. Limitation of Liability</h2>
              <p>
                Neither Musawwir Art nor any other party involved in creating the Website will be liable for any incidental, special, exemplary or consequential damages arising out of or in connection with these Terms or from the use of or inability to use the Website.
              </p>
            </section>

            <section id="jurisdiction" className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">9. Controlling Law and Jurisdiction</h2>
              <p>
                These Terms and any action related thereto will be governed by the laws of India without regard to its conflict of law’s provisions. The exclusive jurisdiction and venue of any action with respect to the subject matter of these Terms will be the state courts located at Karnataka, India.
              </p>
            </section>

            <hr className="border-stone-100" />

            <section className="space-y-4 pt-4">
              <h2 className="text-xl font-bold uppercase tracking-widest text-stone-900">Contacting Us</h2>
              <p>
                If you have any questions about these Terms, please contact Musawwir Art at:
              </p>
              <div className="bg-stone-50 p-6 rounded-sm border border-stone-100 space-y-2">
                <p className="font-bold text-stone-900">Musawwir Art Private Limited</p>
                <p className="text-sm">#198, CMH Road, 2nd Floor, Suite No.783,</p>
                <p className="text-sm">Indiranagar, Bangalore, Karnataka, India 560 038</p>
                <p className="text-sm pt-4">Email: musawwirart1@gmail.com</p>
                <p className="text-sm">WhatsApp: +971 5854 15011</p>
              </div>
            </section>

          </div>
        </main>

      </div>
    </div>
  );
};

export default TermsOfService;
