services:
  backend:
    build: ./Backend
    container_name: musawwir-backend
    restart: unless-stopped
    env_file: ./Backend/.env
    volumes:
      - /var/www/musawwir_data/public:/app/public
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.musawwir-api.rule=Host(`api.musawwirart.com`)"
          - "traefik.http.routers.musawwir-api.entrypoints=websecure"
          - "traefik.http.routers.musawwir-api.tls=true"
          - "traefik.http.routers.musawwir-api.tls.certresolver=myresolver"
          - "traefik.http.services.musawwir-api.loadbalancer.server.port=3000"
          - "traefik.http.middlewares.musawwir-cors.headers.accessControlAllowMethods=GET,POST,OPTIONS,PUT,DELETE"
          - "traefik.http.middlewares.musawwir-cors.headers.accessControlAllowOriginList=*"
          - "traefik.http.middlewares.musawwir-cors.headers.accessControlAllowHeaders=*"
          - "traefik.http.middlewares.musawwir-cors.headers.accessControlMaxAge=100"
          - "traefik.http.middlewares.musawwir-cors.headers.addVaryHeader=true"
          - "traefik.http.routers.musawwir-api.middlewares=musawwir-cors"
  frontend:
    build: 
      context: ./Frontend
      args:
        - VITE_API_URL=https://api.musawwirart.com
    container_name: musawwir-frontend
    restart: unless-stopped
    env_file: ./Frontend/.env
    volumes:
      - /var/www/musawwir_data/public/uploads:/usr/share/nginx/html/uploads:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musawwir-fe.rule=Host(`art.musawwirart.com`) || Host(`www.art.musawwirart.com`)"
      - "traefik.http.routers.musawwir-fe.entrypoints=websecure"
      - "traefik.http.routers.musawwir-fe.tls=true"
      - "traefik.http.routers.musawwir-fe.tls.certresolver=myresolver"
      - "traefik.http.services.musawwir-fe.loadbalancer.server.port=80"

networks:
  traefik:
    external: true